### ISSUE TITLE
Does the BinaryProtocol write its buffer onto the transport?

### ISSUE THREAD

**Issue by Ponyets** [radekg/thrift-js-binary-protocol#2]
Excuse me.
I can't find anywhere the protocol writes its buffer to the transport. It seems that the transport is never used by the protocol. 
Do I misunderstand your code?

**Comment by radekg** [comment]
No, you understand right. This was an adaptation of one of the existing protocols at the time of writing this code. It is highly possible that the original implementation did not do any of that either.
These JS protocols have went through so many changes, difficult to say what state this is in now.
