### ISSUE TITLE
Uncaught TypeError: this.output.getTransport is not a function(…)

### ISSUE THREAD

**Issue by jayku4u** [radekg/thrift-js-binary-protocol#3]
Hi,

I was trying to use JS client and cpp Server with TBinaryProtocol in the browser. I included your library and couldn't get the same app working. I ended up with the below error.

```
Calculator.js:122 Uncaught TypeError: this.output.getTransport is not a function(…)
```

But if i replace with the TJSONProtocol, it works as expected. 
Can you please let me know where am i going wrong w.r.t TBinaryProtocol?

Sample app attached.
[thrift-js-binary-protocol.zip](https://github.com/gossiperl/thrift-js-binary-protocol/files/243485/thrift-js-binary-protocol.zip)

**Comment by radekg** [comment]
@jayku4u This code has been written a while ago while Thrift for JS was getting a lot of attention. The implementation might not be working correctly with the recent Thrift releases. I do not maintain this code actively anymore but a PR is welcomed.
